# Generated by Django 5.1.5 on 2025-04-03 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter_analytics', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voter',
            old_name='precinct_number',
            new_name='precinct',
        ),
        migrations.RenameField(
            model_name='voter',
            old_name='date_of_registration',
            new_name='registration_date',
        ),
        migrations.RenameField(
            model_name='voter',
            old_name='v20state',
            new_name='voted_2020_state',
        ),
        migrations.RenameField(
            model_name='voter',
            old_name='v21primary',
            new_name='voted_2021_primary',
        ),
        migrations.RenameField(
            model_name='voter',
            old_name='v21town',
            new_name='voted_2021_town',
        ),
        migrations.RenameField(
            model_name='voter',
            old_name='v22general',
            new_name='voted_2022_general',
        ),
        migrations.RenameField(
            model_name='voter',
            old_name='v23town',
            new_name='voted_2023_town',
        ),
        migrations.RemoveField(
            model_name='voter',
            name='party_affiliation',
        ),
        migrations.AddField(
            model_name='voter',
            name='party',
            field=models.CharField(default='U ', max_length=2),
        ),
    ]
