# Generated by Django 5.1.5 on 2025-04-04 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter_analytics', '0002_rename_precinct_number_voter_precinct_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='voter',
            options={'ordering': ['last_name', 'first_name']},
        ),
        migrations.AlterField(
            model_name='voter',
            name='party',
            field=models.CharField(choices=[('D', 'Democrat'), ('R', 'Republican'), ('U', 'Unenrolled/Independent'), ('L', 'Libertarian'), ('G', 'Green-Rainbow')], default='U', max_length=2),
        ),
        migrations.AlterField(
            model_name='voter',
            name='voter_score',
            field=models.IntegerField(default=0),
        ),
    ]
