# Generated by Django 5.1.5 on 2025-04-04 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter_analytics', '0003_alter_voter_options_alter_voter_party_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='voter',
            options={},
        ),
        migrations.AlterField(
            model_name='voter',
            name='party',
            field=models.CharField(default='U ', max_length=2),
        ),
        migrations.AlterField(
            model_name='voter',
            name='voter_score',
            field=models.IntegerField(),
        ),
    ]
