# Generated by Django 5.1.5 on 2025-03-04 20:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini_fb', '0004_alter_statusmessage_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statusmessage',
            old_name='message',
            new_name='text',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='profilepic',
        ),
        migrations.RemoveField(
            model_name='statusmessage',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='profile',
            name='image_file',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='statusmessage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_file', models.ImageField(upload_to='uploads/images/')),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('caption', models.TextField(blank=True, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='mini_fb.profile')),
            ],
        ),
        migrations.CreateModel(
            name='StatusImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_messages', to='mini_fb.image')),
                ('status_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_images', to='mini_fb.statusmessage')),
            ],
        ),
    ]
