# Generated by Django 5.1.5 on 2025-03-05 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini_fb', '0005_rename_message_statusmessage_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statusimage',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statusimage', to='mini_fb.image'),
        ),
        migrations.AlterField(
            model_name='statusimage',
            name='status_message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statusimage', to='mini_fb.statusmessage'),
        ),
    ]
