# Generated by Django 5.1.5 on 2025-03-06 02:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini_fb', '0006_alter_statusimage_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='caption',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='image_file',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='image',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mini_fb.profile'),
        ),
        migrations.AlterField(
            model_name='image',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='statusimage',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mini_fb.image'),
        ),
        migrations.AlterField(
            model_name='statusimage',
            name='status_message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mini_fb.statusmessage'),
        ),
    ]
