# Generated by Django 5.1.5 on 2025-03-06 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mini_fb', '0007_alter_image_caption_alter_image_image_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='caption',
        ),
    ]
