# Generated by Django 5.1.5 on 2025-03-06 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini_fb', '0008_remove_image_caption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
        migrations.AlterField(
            model_name='statusmessage',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mini_fb.profile'),
        ),
        migrations.AlterField(
            model_name='statusmessage',
            name='text',
            field=models.CharField(max_length=300),
        ),
    ]
